version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:11.3
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  drf-api:
    container_name: drf-api
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      - postgres
    links:
      - "postgres:postgres"
    environment:
      - DB_HOST=postgres
    entrypoint: ./entrypoint-dev.sh
